_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

app:
    resource: "../src/Controller/"
    type: annotation

# club:
#     path: /association
#     defaults:
#         _controller: AppBundle:DefaultController:show
#     requirements:
#         id: \d+

new_page:
    path: /club-page/{id}
    controller: App\Controller\DefaultController:showAction

